/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ItemListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author admin pc
 */
public class v_estimasisusu extends javax.swing.JFrame {

    /**
     * Creates new form v_estimasisusu
     */
    public v_estimasisusu() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
        public JButton getback_btn() {
        return back_btn;
    }
        public JButton getsimpan_btn() {
        return simpan_btn;
    }
        public JTable gettabel_estimasi() {
        return tabel_estimasi;
    }
        public JTextField getidestimasi_tf() {
        return idestimasi_tf;
    }
        public JComboBox getidpsusu_combo() {
        return idpsusu_combo;
    }
        public void comboidpsusu(String[] data){
        int x = 0;
        while (x < data.length) {
            idpsusu_combo.addItem(data[x]);
            x++;
        }
    }
        public void setOnClikidpsusu(ItemListener a) {
        idpsusu_combo.addItemListener(a);
    }
        public String getSelectedidpsusu() {
        return idpsusu_combo.getSelectedItem().toString();
    }
        public JTextField getsusuperbulan_tf() {
        return susuperbulan_tf;
    }
        public void setsusuperbulan_tf(String a) {
        susuperbulan_tf.setText(a);
    }
        public void laktasi1_tf(String a) {
        susuperbulan_tf.setText(a);
    }
        public JTextField getlaktasi1_tf() {
        return laktasi1_tf;
    }
        public void laktasi2_tf(String a) {
        susuperbulan_tf.setText(a);
    }
        public JTextField getlaktasi2_tf() {
        return laktasi2_tf;
    }
        public void laktasi3_tf(String a) {
        susuperbulan_tf.setText(a);
    }
        public JTextField getlaktasi3_tf() {
        return laktasi3_tf;
    }
        public void laktasi4_tf(String a) {
        susuperbulan_tf.setText(a);
    }
        public JTextField getlaktasi4_tf() {
        return laktasi4_tf;
    }
        public void laktasi5_tf(String a) {
        susuperbulan_tf.setText(a);
    }
        public JTextField getlaktasi5_tf() {
        return laktasi5_tf;
    }
        public void laktasi6_tf(String a) {
        susuperbulan_tf.setText(a);
    }
        public JTextField getlaktasi6_tf() {
        return laktasi6_tf;
    }
        public void laktasi7_tf(String a) {
        susuperbulan_tf.setText(a);
    }
        public JTextField getlaktasi7_tf() {
        return laktasi7_tf;
    }
        public void laktasi8_tf(String a) {
        susuperbulan_tf.setText(a);
    }
        public JTextField getlaktasi8_tf() {
        return laktasi8_tf;
    }
        public void laktasi9_tf(String a) {
        susuperbulan_tf.setText(a);
    }
        public JTextField getlaktasi9_tf() {
        return laktasi9_tf;
    }
        public void laktasi10_tf(String a) {
        susuperbulan_tf.setText(a);
    }
        public JTextField getlaktasi10_tf() {
        return laktasi10_tf;
    }
        public void kosong() {
        idpsusu_combo.setActionCommand(null);
        susuperbulan_tf.setText(null);
        laktasi1_tf.setText(null);
        laktasi2_tf.setText(null);
        laktasi3_tf.setText(null);
        laktasi4_tf.setText(null);
        laktasi5_tf.setText(null);
        laktasi6_tf.setText(null);
        laktasi7_tf.setText(null);
        laktasi8_tf.setText(null);
        laktasi9_tf.setText(null);
        laktasi10_tf.setText(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        laktasi1_tf = new javax.swing.JTextField();
        idestimasi_tf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        susuperbulan_tf = new javax.swing.JTextField();
        back_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_estimasi = new javax.swing.JTable();
        simpan_btn = new javax.swing.JButton();
        idpsusu_combo = new javax.swing.JComboBox<>();
        laktasi2_tf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        laktasi5_tf = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        laktasi4_tf = new javax.swing.JTextField();
        laktasi3_tf = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        laktasi6_tf = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        laktasi7_tf = new javax.swing.JTextField();
        laktasi8_tf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        laktasi9_tf = new javax.swing.JTextField();
        laktasi10_tf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel9.setText("Id Estimasi Susu    :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        getContentPane().add(laktasi1_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 40, 30));
        getContentPane().add(idestimasi_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 150, 30));

        jLabel10.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel10.setText("Id Produksi Susu    :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel11.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel11.setText("Produk Susu / Bulan :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        getContentPane().add(susuperbulan_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 150, 30));

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        getContentPane().add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        tabel_estimasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_estimasi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 1030, 110));

        simpan_btn.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        simpan_btn.setText("Simpan");
        getContentPane().add(simpan_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, -1, -1));

        idpsusu_combo.setFont(new java.awt.Font("OCR-B 10 BT", 0, 11)); // NOI18N
        idpsusu_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah Satu" }));
        getContentPane().add(idpsusu_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 150, 30));
        getContentPane().add(laktasi2_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 40, 30));

        jLabel13.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel13.setText("Bulan Laktasi 2 :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        getContentPane().add(laktasi5_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 40, 30));

        jLabel17.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel17.setText("Bulan Laktasi 5 :");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel19.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel19.setText("Bulan Laktasi 4 :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel20.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel20.setText("Bulan Laktasi 3 :");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));
        getContentPane().add(laktasi4_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 40, 30));
        getContentPane().add(laktasi3_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 40, 30));

        jLabel21.setFont(new java.awt.Font("OCR-B 10 BT", 0, 24)); // NOI18N
        jLabel21.setText("Data Estimasi Susu");
        jPanel1.add(jLabel21);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 280, 40));

        jLabel22.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel22.setText("Bulan Laktasi 1 :");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel27.setText("L/Bulan");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jLabel32.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel32.setText("L/Bulan");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jLabel33.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel33.setText("L/Bulan");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        jLabel34.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel34.setText("L/Bulan");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        jLabel40.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel40.setText("L/Bulan");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 270, 210));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(laktasi6_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 40, 30));

        jLabel18.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel18.setText("Bulan Laktasi 6 :");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel8.setText("Bulan Laktasi 7 :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        jPanel3.add(laktasi7_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 40, 30));
        jPanel3.add(laktasi8_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 40, 30));

        jLabel16.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel16.setText("Bulan Laktasi 8 :");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel15.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel15.setText("Bulan Laktasi 9 :");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        jPanel3.add(laktasi9_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 40, 30));
        jPanel3.add(laktasi10_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 40, 30));

        jLabel14.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel14.setText("Bulan Laktasi 10:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel36.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel36.setText("L/Bulan");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jLabel37.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel37.setText("L/Bulan");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabel38.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel38.setText("L/Bulan");
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        jLabel41.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel41.setText("L/Bulan");
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel39.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel39.setText("L/Bulan");
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 270, 210));

        jLabel35.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel35.setText("/L");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 30, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ternak sapi perah.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_estimasisusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_estimasisusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_estimasisusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_estimasisusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_estimasisusu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JTextField idestimasi_tf;
    private javax.swing.JComboBox<String> idpsusu_combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField laktasi10_tf;
    private javax.swing.JTextField laktasi1_tf;
    private javax.swing.JTextField laktasi2_tf;
    private javax.swing.JTextField laktasi3_tf;
    private javax.swing.JTextField laktasi4_tf;
    private javax.swing.JTextField laktasi5_tf;
    private javax.swing.JTextField laktasi6_tf;
    private javax.swing.JTextField laktasi7_tf;
    private javax.swing.JTextField laktasi8_tf;
    private javax.swing.JTextField laktasi9_tf;
    private javax.swing.JButton simpan_btn;
    private javax.swing.JTextField susuperbulan_tf;
    private javax.swing.JTable tabel_estimasi;
    // End of variables declaration//GEN-END:variables
}
