/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;

/**
 *
 * @author admin pc
 */
public class v_how_to_play extends javax.swing.JFrame {

    /**
     * Creates new form v_how_to_play
     */
    public v_how_to_play() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public JButton getback() {
        return back;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        how_to_play = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        background_v_how_to_play = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        how_to_play.setFont(new java.awt.Font("OCR-B 10 BT", 0, 48)); // NOI18N
        how_to_play.setText("HOW TO PLAY?");
        getContentPane().add(how_to_play, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        jLabel1.setFont(new java.awt.Font("OCR-B 10 BT", 0, 18)); // NOI18N
        jLabel1.setText("ID PRODUKSI SUSU TERSEBUT, klik simpan, lalu klik back.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("OCR-B 10 BT", 0, 18)); // NOI18N
        jLabel2.setText("1. Klik Start dan tunggu Loading Tersebut!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("OCR-B 10 BT", 0, 18)); // NOI18N
        jLabel3.setText("dan bulan laktasi 1 - 10 dengan otomatis, dan klik simpan, lalu klik back.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("OCR-B 10 BT", 0, 18)); // NOI18N
        jLabel4.setText("2. Pilih Button Produksi SUSU terlebuh dahulu, dan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("OCR-B 10 BT", 0, 18)); // NOI18N
        jLabel5.setText("inputkan data yang diminta tersebut, untuk");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("OCR-B 10 BT", 0, 18)); // NOI18N
        jLabel6.setText("total, rata - rata, produksi susu per bulan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("OCR-B 10 BT", 0, 18)); // NOI18N
        jLabel8.setText("akan keluar otomatis, dan ingat ingat");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("OCR-B 10 BT", 0, 18)); // NOI18N
        jLabel9.setText("dan lihatlah estimasi bulan 1 - 10 apakah sudah mencukupi stansarisasi tersebut.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        jLabel10.setFont(new java.awt.Font("OCR-B 10 BT", 0, 18)); // NOI18N
        jLabel10.setText("Combo box yang disiapkan, lalu akan keluar produksi susu per bulan");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("OCR-B 10 BT", 0, 18)); // NOI18N
        jLabel11.setText("3. Pilih Button Estimasi SUSU, dan pilih ID PRODUKSI anda pada");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("OCR-B 10 BT", 0, 18)); // NOI18N
        jLabel12.setText("dengan otomatis. SELAMAT MENCOBA.");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        jLabel13.setFont(new java.awt.Font("OCR-B 10 BT", 0, 18)); // NOI18N
        jLabel13.setText("yang disiapkan, lalu akan keluar produksi susu per bulan, dan standarisasi ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel14.setFont(new java.awt.Font("OCR-B 10 BT", 0, 18)); // NOI18N
        jLabel14.setText("produksi susu/bulan tersebut dengan otomatis, dan klik simpan, lalu klik back");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        jLabel15.setFont(new java.awt.Font("OCR-B 10 BT", 0, 18)); // NOI18N
        jLabel15.setText("4. Pilih Button Standarisasi SUSU, dan pilih ID PRODUKSI anda pada Combo box");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel16.setFont(new java.awt.Font("OCR-B 10 BT", 0, 18)); // NOI18N
        jLabel16.setText("5. Pilih Button Kualitas SUSU, dan pilih ID PRODUKSI anda pada Combo box, dan inputkan ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel17.setFont(new java.awt.Font("OCR-B 10 BT", 0, 18)); // NOI18N
        jLabel17.setText("bulan laktasi ke berapa, dan piih cuaca tersebut, lalu akan mucul kualitas susu tersebut");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1020, 530));

        background_v_how_to_play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ternak sapi perah.jpg"))); // NOI18N
        getContentPane().add(background_v_how_to_play, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_how_to_play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_how_to_play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_how_to_play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_how_to_play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_how_to_play().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel background_v_how_to_play;
    private javax.swing.JLabel how_to_play;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
