/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ItemListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author admin pc
 */
public class v_kualitas extends javax.swing.JFrame {

    /**
     * Creates new form v_kualitas
     */
    public v_kualitas() {
        initComponents();
        setLocationRelativeTo(null);
    }
        public JButton getback_btn() {
        return back_btn;
    }
        public JButton getsimpan_btn() {
        return simpan_btn;
    }
        public JTable gettabel_kualitas() {
        return tabel_kualitas;
    }
        public JTextField getidkualitas_tf() {
        return idkualitas_tf;
    }
        public JComboBox getidpsusu_combo() {
        return idpsusu_combo;
    }
        public void comboidpsusu(String[] data){
        int x = 0;
        while (x < data.length) {
            idpsusu_combo.addItem(data[x]);
            x++;
        }
    }
        public void setOnClikidpsusu(ItemListener a) {
        idpsusu_combo.addItemListener(a);
    }
        public String getSelectedidpsusu() {
        return idpsusu_combo.getSelectedItem().toString();
    }
        public JTextField getbulanlaktasi_tf() {
        return bulanlaktasi_tf;
    }
        public JComboBox getcuaca_combo() {
        return cuaca_combo;
    }
        public void combocuaca(String[] data){
        int x = 0;
        while (x < data.length) {
            cuaca_combo.addItem(data[x]);
            x++;
        }
    }
        public void setOnClikcuaca(ItemListener a) {
        cuaca_combo.addItemListener(a);
    }
        public String getSelectedcuaca() {
        return cuaca_combo.getSelectedItem().toString();
    }
        public JTextField getkualitas_tf() {
        return kualitas_tf;
    }
        public void setkualitas_tf(String a) {
        kualitas_tf.setText(a);
    }
        public void kosong() {
        idpsusu_combo.setActionCommand(null);
        bulanlaktasi_tf.setText(null);
        cuaca_combo.setActionCommand(null);
        kualitas_tf.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bulanlaktasi_tf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cuaca_combo = new javax.swing.JComboBox<>();
        kualitas_tf = new javax.swing.JTextField();
        idkualitas_tf = new javax.swing.JTextField();
        idpsusu_combo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_kualitas = new javax.swing.JTable();
        back_btn = new javax.swing.JButton();
        simpan_btn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("OCR-B 10 BT", 0, 24)); // NOI18N
        jLabel13.setText("Data Kualitas Susu");
        jPanel1.add(jLabel13);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 270, 40));

        jLabel9.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel9.setText("Id Produksi Susu :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));
        getContentPane().add(bulanlaktasi_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 150, 30));

        jLabel10.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel10.setText("Bulan Laktasi Ke :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel11.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel11.setText("1.Kemarau");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        jLabel12.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel12.setText("Kualitas Susu    :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel14.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel14.setText("Id Kualitas Susu :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        cuaca_combo.setFont(new java.awt.Font("OCR-B 10 BT", 0, 11)); // NOI18N
        cuaca_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah Satu" }));
        getContentPane().add(cuaca_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 150, 30));
        getContentPane().add(kualitas_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 150, 30));
        getContentPane().add(idkualitas_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 150, 30));

        idpsusu_combo.setFont(new java.awt.Font("OCR-B 10 BT", 0, 11)); // NOI18N
        idpsusu_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah Satu" }));
        getContentPane().add(idpsusu_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 150, 30));

        tabel_kualitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_kualitas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 610, 160));

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        getContentPane().add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        simpan_btn.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        simpan_btn.setText("Simpan");
        simpan_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_btnActionPerformed(evt);
            }
        });
        getContentPane().add(simpan_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        jLabel15.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel15.setText("2.Hujan");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, -1));

        jLabel16.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel16.setText("Cuaca            :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ternak sapi perah.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpan_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpan_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_kualitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_kualitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_kualitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_kualitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_kualitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JTextField bulanlaktasi_tf;
    private javax.swing.JComboBox<String> cuaca_combo;
    private javax.swing.JTextField idkualitas_tf;
    private javax.swing.JComboBox<String> idpsusu_combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kualitas_tf;
    private javax.swing.JButton simpan_btn;
    private javax.swing.JTable tabel_kualitas;
    // End of variables declaration//GEN-END:variables
}
