/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JProgressBar;
import javax.swing.Timer;

import java.awt.event.*;

/**
 *
 * @author admin pc
 */
public class v_loading extends javax.swing.JFrame {

    /**
     * Creates new form v_loading
     */
    
    public v_loading() {
        initComponents();
        setLocationRelativeTo(null);
        
    }
    
    public JProgressBar getloading() {
        return loading;
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        loading = new javax.swing.JProgressBar();
        background_v_loading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("OCR-B 10 BT", 0, 36)); // NOI18N
        jLabel1.setText("MOHON TUNGGU . . . ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));
        getContentPane().add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 1130, 30));

        background_v_loading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ternak sapi perah.jpg"))); // NOI18N
        getContentPane().add(background_v_loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_loading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_v_loading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar loading;
    // End of variables declaration//GEN-END:variables

//    private void act() {
//        action = new ActionListener(){
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                loading.setValue(loading.getValue()+2);
//                loading.setStringPainted(true);
//                if (loading.getPercentComplete()== 1.00 ) {
//                    timer.stop();
//                    st = new v_start();
//                    st.setVisible(true);
//                    dispose();
//                    
//                }
//            }
//            
//        };
//        this.dispose();
//    }
}
