/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin pc
 */
public class v_produksusu extends javax.swing.JFrame {

    /**
     * Creates new form v_produksusu
     */
    public v_produksusu() {
        initComponents();
        setLocationRelativeTo(null);
    }
        public JButton getback_btn() {
        return back_btn;
    }
        public JButton getsimpan_btn() {
        return simpan_btn;
    }
        public JTable gettabel_sususapi() {
        return tabel_sususapi;
    }
        public JTextField getidsapi_tf() {
        return idsapi_tf;
    }
        public JTextField getnama_tf() {
        return nama_tf;
    }
        public JTextField getumursapi_tf() {
        return umursapi_tf;
    }
        public JComboBox getpakantambahan_combo() {
        return pakantambahan_combo;
    }
        public JTextField getperlaktasi_tf() {
        return perlaktasi_tf;
    }
        public JTextField getproduksisusu1_tf() {
        return produksisusu1_tf;
    }
        public void total2(KeyListener a){
        produksisusu1_tf.addKeyListener(a);
    }
        public JTextField getproduksisusu2_tf() {
        return produksisusu2_tf;
    }
        public void total1(KeyListener a){
        produksisusu2_tf.addKeyListener(a);
    }
        public JTextField getproduksisusu3_tf() {
        return produksisusu3_tf;
    }
        public void total(KeyListener a){
        produksisusu3_tf.addKeyListener(a);
    }
        public JTextField gettotalproduksi_tf() {
        return totalproduksi_tf;
    }
        public void ratarata(KeyListener a){
        totalproduksi_tf.addKeyListener(a);
    }
        public JTextField getratarata_tf() {
        return ratarata_tf;
    }
        public void p_susubulan_tf(KeyListener a){
        ratarata_tf.addKeyListener(a);
    }
        public JTextField getp_susubulan_tf() {
        return p_susubulan_tf;
    }
        public void kosong() {
        nama_tf.setText(null);
        umursapi_tf.setText(null);
        pakantambahan_combo.setActionCommand(null);
        perlaktasi_tf.setText(null);
        produksisusu1_tf.setText(null);
        produksisusu2_tf.setText(null);
        produksisusu3_tf.setText(null);
        totalproduksi_tf.setText(null);
        ratarata_tf.setText(null);
        p_susubulan_tf.setText(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ratarata_tf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        produksisusu1_tf = new javax.swing.JTextField();
        produksisusu2_tf = new javax.swing.JTextField();
        produksisusu3_tf = new javax.swing.JTextField();
        totalproduksi_tf = new javax.swing.JTextField();
        simpan_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_sususapi = new javax.swing.JTable();
        back_btn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        p_susubulan_tf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        umursapi_tf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pakantambahan_combo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        idsapi_tf = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        nama_tf = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        perlaktasi_tf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel2.setText("Hasil Perah Siang      :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel3.setText("Id Produksi Susu       :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        ratarata_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratarata_tfActionPerformed(evt);
            }
        });
        getContentPane().add(ratarata_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 120, 30));

        jLabel4.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel4.setText("Pakan Tambahan         :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel5.setText("Periode Laktasi ke     :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel6.setText("/L");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        jLabel7.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel7.setText("Hasil Perah Sore       :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel8.setText("Total Produksi Susu    :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        produksisusu1_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produksisusu1_tfActionPerformed(evt);
            }
        });
        getContentPane().add(produksisusu1_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 120, 30));

        produksisusu2_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produksisusu2_tfActionPerformed(evt);
            }
        });
        getContentPane().add(produksisusu2_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 120, 30));

        produksisusu3_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produksisusu3_tfActionPerformed(evt);
            }
        });
        getContentPane().add(produksisusu3_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 120, 30));

        totalproduksi_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalproduksi_tfActionPerformed(evt);
            }
        });
        getContentPane().add(totalproduksi_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 120, 30));

        simpan_btn.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        simpan_btn.setText("Simpan");
        getContentPane().add(simpan_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, -1, -1));

        tabel_sususapi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_sususapi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 1040, 100));

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        getContentPane().add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        jLabel9.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel9.setText("Rata Rata Susu / Hari  :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        p_susubulan_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_susubulan_tfActionPerformed(evt);
            }
        });
        getContentPane().add(p_susubulan_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 120, 30));

        jLabel10.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel10.setText("Produk Susu / Bulan    :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        umursapi_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umursapi_tfActionPerformed(evt);
            }
        });
        getContentPane().add(umursapi_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 120, 30));

        jLabel11.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel11.setText("Nama                   :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        pakantambahan_combo.setFont(new java.awt.Font("OCR-B 10 BT", 0, 11)); // NOI18N
        pakantambahan_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Katul", "Ampas Tahu", "Kosong" }));
        getContentPane().add(pakantambahan_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 120, 30));

        jLabel12.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel12.setText("Umur Sapi              :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        idsapi_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idsapi_tfActionPerformed(evt);
            }
        });
        getContentPane().add(idsapi_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 120, 30));

        jLabel13.setFont(new java.awt.Font("OCR-B 10 BT", 0, 24)); // NOI18N
        jLabel13.setText("Data Produksi Susu");
        jPanel1.add(jLabel13);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 280, 40));

        jLabel14.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel14.setText("Hasil Perah Pagi       :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel15.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel15.setText("Tahun");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        jLabel16.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel16.setText("/L");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        jLabel17.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel17.setText("/L");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));

        jLabel18.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel18.setText("/L");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, -1, -1));

        jLabel19.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel19.setText("/L");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, -1, -1));

        nama_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_tfActionPerformed(evt);
            }
        });
        getContentPane().add(nama_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 120, 30));

        jLabel20.setFont(new java.awt.Font("OCR-B 10 BT", 0, 14)); // NOI18N
        jLabel20.setText("/L");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        perlaktasi_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perlaktasi_tfActionPerformed(evt);
            }
        });
        getContentPane().add(perlaktasi_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 120, 30));

        jLabel1.setFont(new java.awt.Font("OCR-B 10 BT", 0, 11)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ternak sapi perah.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ratarata_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratarata_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ratarata_tfActionPerformed

    private void produksisusu1_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produksisusu1_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produksisusu1_tfActionPerformed

    private void produksisusu2_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produksisusu2_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produksisusu2_tfActionPerformed

    private void produksisusu3_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produksisusu3_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produksisusu3_tfActionPerformed

    private void totalproduksi_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalproduksi_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalproduksi_tfActionPerformed

    private void p_susubulan_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_susubulan_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_susubulan_tfActionPerformed

    private void umursapi_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umursapi_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_umursapi_tfActionPerformed

    private void idsapi_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idsapi_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idsapi_tfActionPerformed

    private void nama_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_tfActionPerformed

    private void perlaktasi_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perlaktasi_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perlaktasi_tfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_produksusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_produksusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_produksusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_produksusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_produksusu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JTextField idsapi_tf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nama_tf;
    private javax.swing.JTextField p_susubulan_tf;
    private javax.swing.JComboBox<String> pakantambahan_combo;
    private javax.swing.JTextField perlaktasi_tf;
    private javax.swing.JTextField produksisusu1_tf;
    private javax.swing.JTextField produksisusu2_tf;
    private javax.swing.JTextField produksisusu3_tf;
    private javax.swing.JTextField ratarata_tf;
    private javax.swing.JButton simpan_btn;
    private javax.swing.JTable tabel_sususapi;
    private javax.swing.JTextField totalproduksi_tf;
    private javax.swing.JTextField umursapi_tf;
    // End of variables declaration//GEN-END:variables
}
